server:
  port: 8083
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:01022002@localhost:27017/notification-service?authSource=admin
