server:
  port: 8084
  servlet:
    context-path: /post
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://root:01022002@localhost:27017/post-service?authSource=admin

app:
  services:
    profile:
      url: http://localhost:8081/profile
    movie:
      url: http://localhost:8085/movie



