server:
  port: 8087
  servlet:
    context-path: /file
  tomcat:
    max-http-form-post-size: 200MB
spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin
